# Generated by Django 3.1.7 on 2021-03-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='name',
            field=models.CharField(default=123, max_length=1000),
            preserve_default=False,
        ),
    ]
