# Generated by Django 3.1.7 on 2021-03-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0003_blocl'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blocl',
            new_name='Block',
        ),
    ]
