# Generated by Django 3.1.7 on 2021-03-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0004_auto_20210326_1322'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('identity', models.CharField(max_length=1000000)),
                ('vote', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('previousHash', models.CharField(max_length=1000000)),
                ('nonce', models.IntegerField()),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Election.election')),
            ],
        ),
    ]
