# Generated by Django 3.1.7 on 2021-03-27 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Election', '0009_realprevhash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='rejected',
        ),
    ]
